// Retorna uma mensagem aleatória do array ERROR_MESSAGES
function getRandomErrorMessage()

// Retorna uma mensagem aleatória de Combinação de Itens
function getCombinacaoMessages(item01, item02, idMessage)

function loadScene(sceneName)
function fadeToScene(sceneName)
function renderScene(scene)
function renderHotspots()
function handleClick(hotspot, imgElement)
function determineCharacterDialogue(character)
function handleCharacterClick(hotspot)
function showDialogueOptions(options, hotspot)
function selectOption(option, hotspot)
function normalizeOptions(raw)
function getUsedSetForChar(charId)
function advanceModal(e)
function show2Modal(text, hotspot, isResponse = false)
function hideModal()
function showCharacterMessage(nomeCharacter, message)
function unlockClue(clueId)
function showCluesModal()
function addToInventory(itemData)
function removeFromInventory(collectibleId)
function findHotspotById(itemId)
function setHotspotState(sceneName, hotspotId, changes, onfly)
function atualizarImagem(hs,img_src)
function setHotspotsActive(ids = [], isActive = true)
function playAudio(audioFile, callback, waitAudio)
function playAnimation(containerId, spriteUrl, frameWidth, frameHeight, frameCount, duration, posX, posY, mode = "FF")
function debugConditionalOptions(character)